<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Zeroum.DeveloperEvaluation.ABP.Bruna.Application.Contracts\Zeroum.DeveloperEvaluation.ABP.Bruna.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\Zeroum.DeveloperEvaluation.ABP.Bruna.Domain\Zeroum.DeveloperEvaluation.ABP.Bruna.Domain.csproj" />
  </ItemGroup>

</Project>
